// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo1MFzh5CZ3XKgk3-ONyMZDFAnFlF-uR4',
    appId: '1:799919702472:web:c8219f80dc148cee4700fd',
    messagingSenderId: '799919702472',
    projectId: 'ridebridge-743c4',
    authDomain: 'ridebridge-743c4.firebaseapp.com',
    storageBucket: 'ridebridge-743c4.firebasestorage.app',
    measurementId: 'G-NTK7FWCPQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp0VCCtCYGFFlplIiWCy-NmlZlQ3dZv9g',
    appId: '1:799919702472:android:35273e7d17d7ea3b4700fd',
    messagingSenderId: '799919702472',
    projectId: 'ridebridge-743c4',
    storageBucket: 'ridebridge-743c4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClka-h_2GsCW0Hpn08fMgCU2PUPA5-Who',
    appId: '1:799919702472:ios:e4d6cb331bdcc9e14700fd',
    messagingSenderId: '799919702472',
    projectId: 'ridebridge-743c4',
    storageBucket: 'ridebridge-743c4.firebasestorage.app',
    iosBundleId: 'com.example.ridebridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo1MFzh5CZ3XKgk3-ONyMZDFAnFlF-uR4',
    appId: '1:799919702472:web:e75a329435b40ee24700fd',
    messagingSenderId: '799919702472',
    projectId: 'ridebridge-743c4',
    authDomain: 'ridebridge-743c4.firebaseapp.com',
    storageBucket: 'ridebridge-743c4.firebasestorage.app',
    measurementId: 'G-B5GLHVPVH1',
  );
}
